# Generated by Django 4.2.5 on 2023-09-28 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя сертификата')),
                ('photo', models.ImageField(upload_to='photos/certificates/%Y/%m/%d', verbose_name='Фотография')),
                ('sort_key', models.IntegerField(default=0, verbose_name='Приоритет сортировки')),
            ],
            options={
                'ordering': ('sort_key',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=150, verbose_name='Организация')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата окончания')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('sort_key', models.IntegerField(default=0, verbose_name='Приоритет сортировки')),
            ],
            options={
                'ordering': ('sort_key',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('post', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('start_date', models.DateTimeField(verbose_name='Дата трудоустройства')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата увольнения')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('sort_key', models.IntegerField(default=0, verbose_name='Приоритет сортировки')),
            ],
            options={
                'ordering': ('sort_key',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(150)], verbose_name='Возраст')),
                ('photo', models.ImageField(upload_to='photos/avatars/%Y/%m/%d', verbose_name='Фотография')),
                ('habitation', models.CharField(max_length=150, verbose_name='Место проживания')),
            ],
        ),
        migrations.CreateModel(
            name='PetProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя проекта')),
                ('type', models.CharField(max_length=150, verbose_name='Тип проекта')),
                ('photo', models.ImageField(upload_to='photos/projects/%Y/%m/%d', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.CharField(max_length=250, verbose_name='Ссылка на проект')),
                ('sort_key', models.IntegerField(default=0, verbose_name='Приоритет сортировки')),
            ],
            options={
                'ordering': ('sort_key',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skill', models.CharField(max_length=150, verbose_name='Навык')),
                ('sort_key', models.IntegerField(default=0, verbose_name='Приоритет сортировки')),
                ('url', models.CharField(blank=True, max_length=250, verbose_name='Ссылка на проект')),
            ],
            options={
                'ordering': ('sort_key',),
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя социальной сети')),
                ('url', models.CharField(max_length=250, verbose_name='Ссылка')),
            ],
        ),
    ]
