# Generated by Django 4.2.5 on 2023-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_certificates_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='Профессия'),
        ),
    ]
