# Generated by Django 4.2.5 on 2023-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_education_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='details',
            field=models.TextField(blank=True, verbose_name='Детали'),
        ),
    ]
