# Generated by Django 4.2.5 on 2023-09-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_skills_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='profession',
            field=models.CharField(default='backend-разработчик', max_length=150, verbose_name='Профессия'),
            preserve_default=False,
        ),
    ]
