# Generated by Django 4.2.5 on 2023-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_info_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='file_resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
